# Generated by Django 2.2.10 on 2020-05-09 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance_companies', '0003_auto_20200509_0026'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance_assessor', '0004_auto_20200509_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('client_number', models.IntegerField(db_column='client_number', db_index=True, unique=True, verbose_name='Client Number')),
                ('name', models.CharField(db_column='name', max_length=50, verbose_name='Name')),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=15, null=True, verbose_name='Phone Number')),
                ('address', models.TextField(blank=True, db_column='address', null=True, verbose_name='Address')),
                ('user_creation', models.ForeignKey(blank=True, db_column='user_creation_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases_client_creation', to=settings.AUTH_USER_MODEL, verbose_name='User Creation')),
                ('user_modified', models.ForeignKey(blank=True, db_column='user_modified_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases_client_modified', to=settings.AUTH_USER_MODEL, verbose_name='User Modified')),
            ],
            options={
                'db_table': 'client',
                'ordering': ['client_number'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(db_column='case_number', db_index=True, max_length=50, unique=True, verbose_name='Case Number')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Close', 'Close')], db_column='status', max_length=10, verbose_name='Status')),
                ('open_date', models.DateField(db_column='open_date', verbose_name='Open Date')),
                ('close_date', models.DateField(blank=True, db_column='close_date', null=True, verbose_name='Close Date')),
                ('description', models.TextField(blank=True, db_column='description', null=True, verbose_name='Description')),
                ('resolution', models.TextField(blank=True, db_column='resolution', null=True, verbose_name='Resolution')),
                ('assessor', models.ForeignKey(db_column='assessor_fk', on_delete=django.db.models.deletion.PROTECT, related_name='case_assessor', to='insurance_assessor.Assessor', verbose_name='Assessor')),
                ('client', models.ForeignKey(db_column='client_fk', on_delete=django.db.models.deletion.PROTECT, related_name='case_client', to='cases.Client', verbose_name='Client')),
                ('insurance', models.ForeignKey(db_column='insurance_fk', on_delete=django.db.models.deletion.PROTECT, related_name='case_insurance', to='insurance_companies.Insurance', verbose_name='Insurance')),
                ('insurance_consultant', models.ForeignKey(db_column='insurance_consultant_fk', on_delete=django.db.models.deletion.PROTECT, related_name='case_insurance_consultant', to='insurance_companies.InsuranceConsultant', verbose_name='Insurance Consultant')),
                ('user_creation', models.ForeignKey(blank=True, db_column='user_creation_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases_case_creation', to=settings.AUTH_USER_MODEL, verbose_name='User Creation')),
                ('user_modified', models.ForeignKey(blank=True, db_column='user_modified_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases_case_modified', to=settings.AUTH_USER_MODEL, verbose_name='User Modified')),
            ],
            options={
                'db_table': 'case',
                'ordering': ['case_number'],
            },
        ),
    ]
