# Generated by Django 2.2.10 on 2020-05-09 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('Quote', 'Quote'), ('Cover Document', 'Cover Document')], db_column='document_type', max_length=50, verbose_name='Document Type')),
                ('name', models.CharField(db_column='name', max_length=50, verbose_name='Name')),
                ('file_name', models.CharField(blank=True, db_column='file_name', max_length=255, null=True, verbose_name='File Name')),
                ('case', models.ForeignKey(db_column='case_fk', on_delete=django.db.models.deletion.PROTECT, related_name='document_case', to='cases.Case', verbose_name='Case')),
                ('user_creation', models.ForeignKey(blank=True, db_column='user_creation_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases_document_creation', to=settings.AUTH_USER_MODEL, verbose_name='User Creation')),
                ('user_modified', models.ForeignKey(blank=True, db_column='user_modified_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases_document_modified', to=settings.AUTH_USER_MODEL, verbose_name='User Modified')),
            ],
            options={
                'db_table': 'document',
                'ordering': ['case', 'id'],
            },
        ),
    ]
