# Generated by Django 2.2.10 on 2020-05-09 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance_companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceconsultant',
            name='linked_user',
            field=models.ForeignKey(db_column='linked_user_fk', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_consultant_linked_user', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Linked User'),
            preserve_default=False,
        ),
    ]
