# Generated by Django 2.2.10 on 2020-05-09 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_companies', '0002_insuranceconsultant_linked_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insuranceconsultant',
            name='linked_user',
            field=models.OneToOneField(db_column='linked_user_fk', on_delete=django.db.models.deletion.PROTECT, related_name='insurance_consultant_linked_user', to=settings.AUTH_USER_MODEL, verbose_name='Linked User'),
        ),
    ]
