# Generated by Django 2.2.10 on 2020-05-09 00:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insurance_assessor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_column='name', db_index=True, max_length=50, verbose_name='Name')),
                ('phone_number', models.CharField(blank=True, db_column='phone_number', max_length=15, null=True, verbose_name='Phone Number')),
                ('linked_user', models.ForeignKey(db_column='linked_user_fk', on_delete=django.db.models.deletion.PROTECT, related_name='assessor_linked_user', to=settings.AUTH_USER_MODEL, verbose_name='Linked User')),
                ('user_creation', models.ForeignKey(blank=True, db_column='user_creation_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_assessor_assessor_creation', to=settings.AUTH_USER_MODEL, verbose_name='User Creation')),
                ('user_modified', models.ForeignKey(blank=True, db_column='user_modified_fk', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insurance_assessor_assessor_modified', to=settings.AUTH_USER_MODEL, verbose_name='User Modified')),
            ],
            options={
                'db_table': 'assessor',
                'ordering': ['name'],
                'unique_together': {('name', 'linked_user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='insuranceconsultant',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='insuranceconsultant',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='insuranceconsultant',
            name='user_creation',
        ),
        migrations.RemoveField(
            model_name='insuranceconsultant',
            name='user_modified',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
        migrations.DeleteModel(
            name='InsuranceConsultant',
        ),
    ]
