# Generated by Django 2.2.10 on 2020-05-09 00:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insurance_assessor', '0002_auto_20200509_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessor',
            name='linked_user',
            field=models.ForeignKey(db_column='linked_user_fk', on_delete=django.db.models.deletion.PROTECT, related_name='assessor_linked_user', to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Linked User'),
        ),
    ]
